// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/filter/filter.proto

package filter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protos_filter_filter_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60000,
		Name:          "filter.apply",
		Tag:           "bytes,60000,opt,name=apply",
		Filename:      "protos/filter/filter.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// 使用者在欄位上標記: [(filter.apply) = "permission.string"]
	//
	// optional string apply = 60000;
	E_Apply = &file_protos_filter_filter_proto_extTypes[0]
)

var File_protos_filter_filter_proto protoreflect.FileDescriptor

const file_protos_filter_filter_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/filter/filter.proto\x12\x06filter\x1a google/protobuf/descriptor.proto:5\n" +
	"\x05apply\x12\x1d.google.protobuf.FieldOptions\x18\xe0\xd4\x03 \x01(\tR\x05applyB8Z6github.com/hsuanshao/protoc-gen-gofilter/protos/filterb\x06proto3"

var file_protos_filter_filter_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_protos_filter_filter_proto_depIdxs = []int32{
	0, // 0: filter.apply:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_filter_filter_proto_init() }
func file_protos_filter_filter_proto_init() {
	if File_protos_filter_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_filter_filter_proto_rawDesc), len(file_protos_filter_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protos_filter_filter_proto_goTypes,
		DependencyIndexes: file_protos_filter_filter_proto_depIdxs,
		ExtensionInfos:    file_protos_filter_filter_proto_extTypes,
	}.Build()
	File_protos_filter_filter_proto = out.File
	file_protos_filter_filter_proto_goTypes = nil
	file_protos_filter_filter_proto_depIdxs = nil
}
