// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cmd/protoc-gen-gofilter/testdata/optional.proto

package testdata

import (
	_ "github.com/hsuanshao/protoc-gen-gofilter/protos/filter"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionalMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SecretOptional *string                `protobuf:"bytes,1,opt,name=secret_optional,json=secretOptional,proto3,oneof" json:"secret_optional,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OptionalMessage) Reset() {
	*x = OptionalMessage{}
	mi := &file_cmd_protoc_gen_gofilter_testdata_optional_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalMessage) ProtoMessage() {}

func (x *OptionalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_gofilter_testdata_optional_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalMessage.ProtoReflect.Descriptor instead.
func (*OptionalMessage) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDescGZIP(), []int{0}
}

func (x *OptionalMessage) GetSecretOptional() string {
	if x != nil && x.SecretOptional != nil {
		return *x.SecretOptional
	}
	return ""
}

var File_cmd_protoc_gen_gofilter_testdata_optional_proto protoreflect.FileDescriptor

const file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDesc = "" +
	"\n" +
	"/cmd/protoc-gen-gofilter/testdata/optional.proto\x12\x04test\x1a\x1aprotos/filter/filter.proto\"n\n" +
	"\x0fOptionalMessage\x12G\n" +
	"\x0fsecret_optional\x18\x01 \x01(\tB\x19\x82\xfc\xa4\x02\x14test.secret_optionalH\x00R\x0esecretOptional\x88\x01\x01B\x12\n" +
	"\x10_secret_optionalB?Z=github.com/hsuanshao/protoc-gen-gofilter/pkgs/filter/testdatab\x06proto3"

var (
	file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDescData []byte
)

func file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDesc), len(file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDesc)))
	})
	return file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDescData
}

var file_cmd_protoc_gen_gofilter_testdata_optional_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_protoc_gen_gofilter_testdata_optional_proto_goTypes = []any{
	(*OptionalMessage)(nil), // 0: test.OptionalMessage
}
var file_cmd_protoc_gen_gofilter_testdata_optional_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_gofilter_testdata_optional_proto_init() }
func file_cmd_protoc_gen_gofilter_testdata_optional_proto_init() {
	if File_cmd_protoc_gen_gofilter_testdata_optional_proto != nil {
		return
	}
	file_cmd_protoc_gen_gofilter_testdata_optional_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDesc), len(file_cmd_protoc_gen_gofilter_testdata_optional_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_gofilter_testdata_optional_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_gofilter_testdata_optional_proto_depIdxs,
		MessageInfos:      file_cmd_protoc_gen_gofilter_testdata_optional_proto_msgTypes,
	}.Build()
	File_cmd_protoc_gen_gofilter_testdata_optional_proto = out.File
	file_cmd_protoc_gen_gofilter_testdata_optional_proto_goTypes = nil
	file_cmd_protoc_gen_gofilter_testdata_optional_proto_depIdxs = nil
}
