// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cmd/protoc-gen-gofilter/testdata/test.proto

package testdata

import (
	_ "github.com/hsuanshao/protoc-gen-gofilter/protos/filter"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicField   string                 `protobuf:"bytes,1,opt,name=public_field,json=publicField,proto3" json:"public_field,omitempty"`
	PrivateField  string                 `protobuf:"bytes,2,opt,name=private_field,json=privateField,proto3" json:"private_field,omitempty"`
	SecretNumber  int32                  `protobuf:"varint,3,opt,name=secret_number,json=secretNumber,proto3" json:"secret_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_cmd_protoc_gen_gofilter_testdata_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_gofilter_testdata_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetPublicField() string {
	if x != nil {
		return x.PublicField
	}
	return ""
}

func (x *TestMessage) GetPrivateField() string {
	if x != nil {
		return x.PrivateField
	}
	return ""
}

func (x *TestMessage) GetSecretNumber() int32 {
	if x != nil {
		return x.SecretNumber
	}
	return 0
}

var File_cmd_protoc_gen_gofilter_testdata_test_proto protoreflect.FileDescriptor

const file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDesc = "" +
	"\n" +
	"+cmd/protoc-gen-gofilter/testdata/test.proto\x12\x04test\x1a\x1aprotos/filter/filter.proto\"\x9f\x01\n" +
	"\vTestMessage\x12!\n" +
	"\fpublic_field\x18\x01 \x01(\tR\vpublicField\x126\n" +
	"\rprivate_field\x18\x02 \x01(\tB\x11\x82\xfc\xa4\x02\ftest.privateR\fprivateField\x125\n" +
	"\rsecret_number\x18\x03 \x01(\x05B\x10\x82\xfc\xa4\x02\vtest.secretR\fsecretNumberB?Z=github.com/hsuanshao/protoc-gen-gofilter/pkgs/filter/testdatab\x06proto3"

var (
	file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDescData []byte
)

func file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDesc), len(file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDesc)))
	})
	return file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDescData
}

var file_cmd_protoc_gen_gofilter_testdata_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_protoc_gen_gofilter_testdata_test_proto_goTypes = []any{
	(*TestMessage)(nil), // 0: test.TestMessage
}
var file_cmd_protoc_gen_gofilter_testdata_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_gofilter_testdata_test_proto_init() }
func file_cmd_protoc_gen_gofilter_testdata_test_proto_init() {
	if File_cmd_protoc_gen_gofilter_testdata_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDesc), len(file_cmd_protoc_gen_gofilter_testdata_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_gofilter_testdata_test_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_gofilter_testdata_test_proto_depIdxs,
		MessageInfos:      file_cmd_protoc_gen_gofilter_testdata_test_proto_msgTypes,
	}.Build()
	File_cmd_protoc_gen_gofilter_testdata_test_proto = out.File
	file_cmd_protoc_gen_gofilter_testdata_test_proto_goTypes = nil
	file_cmd_protoc_gen_gofilter_testdata_test_proto_depIdxs = nil
}
